name: Generate ZIP File for Download

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate ZIP File for Download
        run: |
          zip -r MagickTes.zip setup ReadMe.txt start_process.bat magicktes.ps1

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v1
        with:
          files: MagickTes.zip  # Upload the generated ZIP file
          tag_name: "MagickTes-v1.0.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the token to authenticate
