name: Generate ZIP File for Download

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate ZIP File for Download
        run: |
          zip -r MagickTes.zip .

      - name: Create a new tag
        id: create_tag
        run: |
          TAG_NAME="v1.0.0"  # Define your tag name (e.g., v1.0.0)
          git config user.name "NeoMatrix14241"
          git config user.email "kylefcapistrano@gmail.com"
          git tag $TAG_NAME  # Create the tag
          git push origin $TAG_NAME  # Push the tag to the repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the token to authenticate

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v1
        with:
          files: MagickTes.zip  # Upload the generated zip file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the token to authenticate
